parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    _instanceof:
        App\Interface\ResolverInterface:
            tags: ['app.vehicle_component_resolver']
        App\Interface\MapperInterface:
            tags: ['app.mapper']

    App\:
        resource: '../src/'
        exclude:
            - '../src/Service/Resolver/VehicleComponentsResolver.php'

    App\Service\Resolver\Components\:
        resource: '../src/Service/Resolver/Components/*'
        public: false

    App\Mapper\Components\:
        resource: '../src/Mapper/Components/*'
        public: false

    App\Mapper\MapperRegistry:
        arguments:
            $mappers: !tagged_iterator app.mapper


    App\Service\Resolver\VehicleComponentsResolver:
        arguments:
            $resolvers: !tagged_iterator app.vehicle_component_resolver
